### ISSUE TITLE
Dodavanje zaposlenika

### ISSUE THREAD

**Issue by adnela** [SoftverInzenjeringETFSA/SI2015Tim2#17]
Komponenta: Dodavanje zaposlenika

commit ID: 
94aa13c48e68cd0e4e5cdb114c70e34495a4390b

Pri dodavanju zaposlenika je moguće: -staviti datum rođenja na datum koji se još nije desio
                                                             -unijeti email u nepravilnom obliku 
                                                             -unijeti broj telefona u nepravilnom obliku

Koraci za reprodukciju problema:
1. Pokrenuti desktop aplikaciju godisnji-odmori
2. Logovati se ako administrator
3. Kliknuti na dugme "Dodaj zaposlenika" sa navedenim nepravilnim podacima
Dobijeni rezultat: Potvrda o uspješnom dodavanju zaposlenika
Očekivan rezultat: Prijava greške

**Comment by kbalic1** [comment]
Rijesen issue sa commitom a2418cb
