### ISSUE TITLE
Dodavanje sektora/ godina osnivanja

### ISSUE THREAD

**Issue by adnela** [SoftverInzenjeringETFSA/SI2015Tim2#18]
Komponenta: Sektori

commit ID:
94aa13c48e68cd0e4e5cdb114c70e34495a4390b

Opis problema:
Pri dodavanju sektora moguće je unijeti bilo koji broj za godinu osnivanja.

Koraci za reprodukciju problema:
1.Pokrenuti desktop aplikaciju godisnji-odmori
2.Logovati se sa podacima administratora
3.Ući u tab Sektori i unijeti bilo koji broj za godinu osnivanja
4.Pritisnuti dugme "Dodaj sektor"
Dobijeni rezultat: Potvrda u uspjesnom dodavanju sektora
Očekivani rezultat: Prijava greške

**Comment by mersedaooad** [comment]
U SRS dokumentu nigdje nije navedeno u kojem opsegu godina osnivanja mora biti
