### ISSUE TITLE
Bolovanje/Neplanirano odsustvo/Godišnji odmor

### ISSUE THREAD

**Issue by adnela** [SoftverInzenjeringETFSA/SI2015Tim2#21]
Komponente:
Bolovanje, Neplanirano odsustvo i Godišnji odmor

commit ID:
94aa13c48e68cd0e4e5cdb114c70e34495a4390b

Opis problema:
Moguće je izabrati bilo koji vremenski interval za kreiranje zahtjeva za bolovanje, npr "datum od" kasniji od "datuma do".

Koraci za reproduciranje problema:
1.Pokrenuti desktop aplikaciju godisnji-odmori
2.Logovati se kao zaposlenik
3.Kliknuti na tab "Bolovanje" ili "Neplanirano odustvo" ili "Godišnji odmor"
4.Izabrati " od" i "do"
5.Kliknuti na dugme "Kreiraj zahtjev" ili "Rezerviši godišnji odmor"
Rezultat: poruka kojom se potvrđuje slanje zahtjeva
Ocekivani rezultat: prijava greske

**Comment by mersedaooad** [comment]
Dupliciran issue broj #17

**Comment by adnela** [comment]
Ne bih rekla da je ovo duplicirani issue, ovdje je bitno da je razmak izmedju datuma bude validan, a u issue br #17 da datum bude validan :D

**Comment by mersedaooad** [comment]
Validacija datuma u cijelo aplikaciji nije uradjena, tako da sve issue koji su vezani za validaciju datuma stavljamo pod jedan.

**Comment by kbalic1** [comment]
Rijesen issue sa commitom a2418cb
