### ISSUE TITLE
Ime i prezime ispod slike

### ISSUE THREAD

**Issue by adnela** [SoftverInzenjeringETFSA/SI2015Tim2#22]
Komponenta:
Pocetna stranica

commit ID:
94aa13c

Opis problema:
Na početnoj stranici ispod slike se ne vidi ime i prezime u cjelosti

Koraci za reproduciranje problema:
1.Pokrenuti desktop aplikaciju godisnji-odmori
2.Logovati se 

Dobijeni rezultat: Prezime se ne vidi u cjelosti
Očekivani rezultat: Ime i prezime korisnika

**Comment by kbalic1** [comment]
Rijesen issue sa commitom a2418cb
