### ISSUE TITLE
Dodavanje istog zaposlenika/sektor više puta

### ISSUE THREAD

**Issue by adnela** [SoftverInzenjeringETFSA/SI2015Tim2#23]
Komponenta:
Zaposlenici i Sektori

commit ID:
94aa13c

Opis problema:
Moguće je dodati korisnika/sektor sa istim podacima više puta.

Koraci za reproduciranje problema:
1.Pokrenuti desktop aplikaciju godisnji-odmori
2.Logovati se kao administrator
3.Ući u tab "Zaposlenici" ili "Sektori"
4.Popuniti podatke i kliknuti na dugme "Dodaj zaposlenika"/"Dodaj sektor"

Dobijeni rezultat: Poruka o uspješnom dodavanju zaposlenika
Očekivani rezultat: Poruka o grešci

**Comment by tcerimagic** [comment]
Braca blizanci koji se isto zovu,zive pod istim krovom i koriste jedan telefon. Apsolutno realna situacija koja ne predstavlja bug. Razlikuju se po username-u i password-u.

**Comment by adnela** [comment]
I koriste jedan email? :D
