### ISSUE TITLE
Uređivanje sektora

### ISSUE THREAD

**Issue by adnela** [SoftverInzenjeringETFSA/SI2015Tim2#24]
Komponenta:
Sektori

commit ID:
94aa13c

Opis problema:
Nakon što se uredi jedan sektor, i klikne na drugi i potom na dugme "Uredi sektor" ne otovore se podaci datog sektora i nema mogućnosti uređenja.

Koraci za reproduciranje problema:
1.Pokrenuti desktop aplikaciju godisnji-odmori
2.Logovati se kao administrator
3.Ući u tab Sektori"
4. Kliknuti na jedan sektor, pa na dugme "Uredi sektor", pa nakon promijenjenih podataka i na dugme "Spasi promjene"
5.Pokušati ponoviti postupak iz tačke 4. sa drugim sektorom

**Comment by kbalic1** [comment]
issue je rjesen sa commitom 864c35d
