### ISSUE TITLE
Izvještaji

### ISSUE THREAD

**Issue by adnela** [SoftverInzenjeringETFSA/SI2015Tim2#25]
Komponenta:
Izvještaji

commit ID:
94aa13c

Opis problema:
Nefunkcionalnost button-a, klikom na dugmad "Godišnji izvještaji" i "Izvještaj o preostalim danima" se ne desi ništa, dok klikom na dugme "Mjesečni izvještaj" se pojavi obavijest o greški, bez objašnjenja zašto je došlo do greške.

Koraci za reproduciranje problema:
1.Pokrenuti desktop aplikaciju godisnji-odmori
2.Logovati se kao administrator
3.Ući u tab "Izvještaji"
4. Kliknuti na spomenute button-e

Dobijeni rezultat: Klikom na dugme "Mjesečni izvještaj" prikaže se poruka o greški, dok se klikom na druga dva dugmeta ne desi ništa.

Očekivani rezultat: generisani izvještaji

**Comment by mersedaooad** [comment]
rijesen sa commit id: 2043ae3a196a499e99a9bc570f19815d82bc1d4c
