### ISSUE TITLE
Prijava na sistem

### ISSUE THREAD

**Issue by adnela** [SoftverInzenjeringETFSA/SI2015Tim2#26]
Komponenta:
Prijava na sistem

commit ID:
94aa13c

Opis problema:
Prijava na sistem sa validnim username-om i passwordom, a prikaže se sljedeća greška :"query did not return a unique result:2" te se nakon klika na dugme OK unutar messageBox-a pojavi isti error, te nakon ponovnog klika na dugme OK korisnik biva uspješno prijavljen.

Koraci za reproduciranje problema:
1.Pokrenuti desktop aplikaciju godisnji-odmori
2.Logovati se kako je navedeno iznad
3.Kliknuti na dugme OK prilikom prikaza prvog error-a
4. Kliknuti na dugme OK prilikom prikaza drugog error-a

Dobijeni rezultat: Nakon prikaza dva errora koji korisniku ne znače ništa, korisnik ipak biva uspješno prijavljen 

Očekivani rezultat: Priijava na sistem bez error-a

**Comment by kbalic1** [comment]
Rijesene logicke greske koje su pravile ovaj problema.
