### ISSUE TITLE
Prikaz informacija o zaposleniku

### ISSUE THREAD

**Issue by adnela** [SoftverInzenjeringETFSA/SI2015Tim2#27]
Komponenta:
Informacije

commit ID:
94aa13c

Opis problema:
Podaci: id zaposlenika, datum rođenja, e-mail. broj telefona nisu prikazane.

Koraci za reproduciranje problema:
1.Pokrenuti desktop aplikaciju godisnji-odmori
2.Logovati se kao zaposlenik
3.Kliknuti na tab "Informacije"

Dobijeni rezultat: Ne prikazivanje navedenih informacija

Očekivani rezultat: Prikaz svih informacija o zaposleniku

**Comment by kbalic1** [comment]
a da li su ti podaci prethodno bili popunjeni?

**Comment by kbalic1** [comment]
Sa popunjenim paramterima, informacije se prikazu.
![image](https://cloud.githubusercontent.com/assets/10118023/15434661/4321821e-1eb8-11e6-9718-b4391092d305.png)
