### ISSUE TITLE
Input broj telefona

### ISSUE THREAD

**Issue by dzemila** [SoftverInzenjeringETFSA/SI2015Tim2#29]
Komponenta:
 Datum u tabu Zaposlenici

Commit ID:
864c35d

Opis problema:
Moguće je unijeti broj telefona slovima

Koraci za reproduciranje problema:
1.Pokrenuti desktop aplikaciju godisnji-odmori
2.Logovati se kao administrator
3.Otvoriti tab "Zaposlenici" 
4.Unijeti broj telefona slovima

Dobijeni rezultat: Poruka o uspješnom dodavanju zaposlenika
Očekivani rezultat: Poruka o nevalidnosti broja telefona

**Comment by kbalic1** [comment]
Dupliciran issue #17
