### ISSUE TITLE
Input email

### ISSUE THREAD

**Issue by dzemila** [SoftverInzenjeringETFSA/SI2015Tim2#30]
Komponenta:
 Email u tabu Zaposlenici

Commit ID:
864c35d

Opis problema:
Moguće je unijeti bilo sta umjesto email-a

Koraci za reproduciranje problema:
1.Pokrenuti desktop aplikaciju godisnji-odmori
2.Logovati se kao administrator
3.Otvoriti tab "Zaposlenici" 
4.Unijeti bilo sta umjesto email-a

Dobijeni rezultat: Poruka o uspješnom dodavanju zaposlenika
Očekivani rezultat: Poruka o nevalidnosti email-a

**Comment by kbalic1** [comment]
Dupliciran issue #17
