### ISSUE TITLE
Edit ID-a

### ISSUE THREAD

**Issue by dzemila** [SoftverInzenjeringETFSA/SI2015Tim2#31]
Komponenta:
 ID u listi Zaposlenika

Commit ID:
864c35d

Opis problema:
Moguće je promijeniti ID u listi Zaposlenika

Koraci za reproduciranje problema:
1.Pokrenuti desktop aplikaciju godisnji-odmori
2.Logovati se kao administrator
3.Otvoriti tab "Zaposlenici" 
4.Na desnoj strani prozora u listi Zaposlenika moguce je promijeniti ID zaposlenika 

Dobijeni rezultat: Promijenjen ID zaposlenika
Očekivani rezultat: Nemogucnost promjene ID-ova zaposlenika

**Comment by kbalic1** [comment]
Rijesen issue sa commitom 865e0ec
