### ISSUE TITLE
Novi sektor se ne moze dodati 

### ISSUE THREAD

**Issue by dzemila** [SoftverInzenjeringETFSA/SI2015Tim2#32]
Komponenta:
Sektor

Commit ID:
864c35d

Opis problema:
Kada se doda sektor u tabu Sektori onda kada se vratimo na Zaposlenike ne mozemo taj novi sektor odabrati

Koraci za reproduciranje problema:
1.Pokrenuti desktop aplikaciju godisnji-odmori
2.Logovati se kao administrator
3.Otvoriti tab "Sektori" 
4.Dodati novi sektor
5. Vratiti se na tab Zaposlenici 
6. Pokusati odabrati novi sektor (koji smo mmalocas dodali)

Dobijeni rezultat: Nemogucnost odabira novog sektora
Očekivani rezultat: Mogucnost odabira novog sektora

**Comment by kbalic1** [comment]
Rijesen issue sa commitom 7c98292
