### ISSUE TITLE
Mjesecni izvjestaj

### ISSUE THREAD

**Issue by dzemila** [SoftverInzenjeringETFSA/SI2015Tim2#33]
Komponenta:
 Mjesecni izvjestaj u tabu Izvjestaji

Commit ID:
864c35d

Opis problema:
Klikom na dugme Mejsecni izvjestaj otvori se greska prozor obavjestenja

Koraci za reproduciranje problema:
1.Pokrenuti desktop aplikaciju godisnji-odmori
2.Logovati se kao administrator
3.Otvoriti tab "Izvjestaji" 
4.Kliknuti na dugme Mjesecni izvjestaj

Dobijeni rezultat: Poruka o gresci
Očekivani rezultat: Mjesecni izvjestaj

**Comment by kbalic1** [comment]
Dupliciran issue #25
