### ISSUE TITLE
Godisnji Izvjestaj

### ISSUE THREAD

**Issue by dzemila** [SoftverInzenjeringETFSA/SI2015Tim2#34]
Komponenta:
 Godisnji izvjestaj u tabu Izvjestaji

Commit ID:
864c35d

Opis problema:
Klikom na dugme Godisnji izvjestaj nista se ne desi

Koraci za reproduciranje problema:
1.Pokrenuti desktop aplikaciju godisnji-odmori
2.Logovati se kao administrator
3.Otvoriti tab "Izvjestaji" 
4.Kliknuti na dugme Godisnji izvjestaj

Dobijeni rezultat: Nista
Očekivani rezultat: Godisnji izvjestaj

**Comment by kbalic1** [comment]
Dupliciran issue #25
