### ISSUE TITLE
Izvjestaj o preostalim danima

### ISSUE THREAD

**Issue by dzemila** [SoftverInzenjeringETFSA/SI2015Tim2#35]
Komponenta:
 Izvjestaj o preostalim danima u tabu Izvjestaji

Commit ID:
864c35d

Opis problema:
Klikom na dugme Izvjestaj o preostalim danima nista se ne desi 

Koraci za reproduciranje problema:
1.Pokrenuti desktop aplikaciju godisnji-odmori
2.Logovati se kao administrator
3.Otvoriti tab "Izvjestaji" 
4.Kliknuti na dugme Izvjestaj o preostalim danima

Dobijeni rezultat: Nista
Očekivani rezultat: Izvjestaj o preostalim danima

**Comment by kbalic1** [comment]
Dupliciran issue #25
