### ISSUE TITLE
Help opcija

### ISSUE THREAD

**Issue by dzemila** [SoftverInzenjeringETFSA/SI2015Tim2#36]
Komponenta:
Help opcija 

Commit ID:
864c35d

Opis problema:
Klikom na opciju Help i odabirom Upustvo nista se ne desi 

Koraci za reproduciranje problema:
1.Pokrenuti desktop aplikaciju godisnji-odmori
2.Logovati se kao administrator
3.Otvoriti tab "Izvjestaji" 
4.Odabrati opciju Help
5.Odabrati opciju Upustvo

Dobijeni rezultat: Nista
Očekivani rezultat: Upustvo za nesto

**Comment by kbalic1** [comment]
Dupliciran issue #19
