### ISSUE TITLE
Broj karaktera u Opisu sektora veci od 255

### ISSUE THREAD

**Issue by srepuh** [SoftverInzenjeringETFSA/SI2015Tim2#38]
Komponenta:
ManagementMainWindow

Opis problema:
Prilikom dodavanja novog sektora kada se unese vise od 255 karaktera za "Opis sektora" ne moze da se sacuva sektor, ne prikaze nikakvu poruku o greski, dugme jednostavno ne radi.
Isto vrijedi za sve vrijednosti pri unosu uposlenika.

Koraci za reprodukciju:
1. Logovati se kao menadzer
2. Kliknuti na tab "Sektor"
3. Unijeti vise od 255 karaktera za "Opis sektora"
3. Kliknuti na "Dodaj sektor"

Dobijeni rezultat:
Forma ne reagira ni na jednu komandu

Ocekivani rezultat:
Poruka da je broj karaktera prevelik ili uspjesno dodavanje sektora

**Comment by kbalic1** [comment]
Rijesen issue sa commitom 5623b2a
