### ISSUE TITLE
Negativan broj preostalih dana za odmor

### ISSUE THREAD

**Issue by srepuh** [SoftverInzenjeringETFSA/SI2015Tim2#40]
Opis problema:
Kada zaposlenik posalje vise zahtjeva za odmore, koji kada se saberu prekoracuju broj preostalih dana godisnjeg, menadzer moze odobriti sve i pojavi se negativan broj preostalih dana godišnjeg odmora.

Koraci za reprodukciju:
1. Logovati se kao zaposlenik
2. Poslati par zahtjeva za odmor koji kada se sabere broj dana bude veci od broja preostalih dana
3. Odjaviti se i logovati kao menadzer
4. Odobriti sve zahtjeve za odmor
5. Odjaviti se i logovati kao zaposlenik
6. Provjeriti broj preostalih dana za odmor

Dobijeni rezultat:
Negativan broj preostalih dana odmora

Ocekivani rezultat:
Da se ne moze odobriti zahtjev ukoliko je broj preostalih dana za odmor jednak nuli

**Comment by kbalic1** [comment]
Menager je uloga da prekontrolise sve zahtjeve, i nakon odobravanja pojedinih, ima pregled koliko je slobodnih dana ostalo zaposleniku te na osnovu tih podataka naredne zahtjeve odobrava ili odbija. Taj faktor je prepusten menageru na odlucivanje.
