### ISSUE TITLE
Pogrešan unos na login formu

### ISSUE THREAD

**Issue by enverpezic** [SoftverInzenjeringETFSA/SI2015Tim2#41]
Komponenta:
Login forma

Opis problema:
Ukoliko unesete pogrešan username i password, zatim kliknete na dugme login pojavi se messagebox koji nema nikakvu poruku. Isti slučaj se dešava ukoliko su prazna polja za unos logina i passworda. 
Password nije case sensitive.

Koraci za reproduciranje problema:
1.Pokrenuti desktop aplikaciju godisnji-odmori
2. Kliknuti na dugme login, ili unijeti pogrešne podatke i zatim kliknuti na login

Dobijeni rezultat: Prazan messagebox bez ikakve poruke.
Očekivani rezultat: Odgovarajuća poruka

**Comment by kbalic1** [comment]
Dupliciran issue #26
