### ISSUE TITLE
Kalendar ne radi ispravno

### ISSUE THREAD

**Issue by srepuh** [SoftverInzenjeringETFSA/SI2015Tim2#42]
Komponenta:
KalendarPregledManagement

Opis problema:
Kad menadzer pregleda zauzete termine u kalendaru nekad prikaze, a nekad ne prikaze zauzete termine, kalendar povremeno ne radi.

Koruci za reprodukciju:
1. Logovati se kao zaposlenik i napraviti zahtjeve za odmor, bolovanje
2. Logovati se kao manadzer odobriti nekoliko od napravljenih zahtjeva
3. Pogledati kalendar (ukoliko bude crveno) ponovo izaci iz aplikacije pa uci

Dobijeni rezultat:
Kalendar nekada prikazuje zauzete termine, nekada ne

Ocekivani rezultat:
Da su pojedini intervali u kalendaru uvijek crveni

**Comment by DinoBabahmetovic** [comment]
kad izadjes iz aplikacije i ponovo udjes odaberi sektor u kojem ti je manager i termini ce se fino prikazati svaki put
