### ISSUE TITLE
Nemogućnost modifikacije sektora

### ISSUE THREAD

**Issue by enverpezic** [SoftverInzenjeringETFSA/SI2015Tim2#43]
Komponenta:
Menadzer forma

Opis problema:
Nakon odabira sektora iz liste sektora i klikom na modifikaciju podaci se smjeste u dio za modifikaciju, problem nastaje ukoliko izvršimo određene promjene nad podacima sektora, a ne promjenimo ime sektora. Zatim klikom na dugme spasi promjene, promjene se ne spašavanju, tj. promjene se samo spašavaju ukoliko i ime sektora promjenimo.

Koraci za reproduciranje problema:
1.Pokrenuti desktop aplikaciju godisnji-odmori
2. Logovatin se kao menadzer
3. Otvoriti tab sa sektorima
4. Odabrati odredjeni sektor i kliknuti na dugme "Uredi sektor"
5. Zatim modifikovati podatke osim naziva sektora
6. Kliknuti na dugme "spasi promjene"

Dobijeni rezultat: 
Nemoguće izvršiti modifikaciju sektora

Očekivani rezultat: 
Mogućnost spašavanja izvršenih promjena

**Comment by kbalic1** [comment]
Issue je dupliciran kao #24 , a svakako je ispravljen sa commitom navedenim u zatvaranju issue-a #24
