### ISSUE TITLE
Menadzer briše sam sebe

### ISSUE THREAD

**Issue by enverpezic** [SoftverInzenjeringETFSA/SI2015Tim2#44]
Komponenta:
Menadzer home

Opis problema:
Kada se prijavi korisnik sa privilegijama menadzera i obrise sam sebe iz liste korisnika, moze jos uvijek da uredjuje ostale stvari, ne izadje iz aplikacije, ocekivano je da odmah izadje iz aplikacije ili da korisnik sa privilegijama menadzera ne moze obrisati sam sebe.

Koraci za reproduciranje problema:
1.Pokrenuti desktop aplikaciju godisnji-odmori
2. Logovatin se kao menadzer
3. Otvoriti tab sa zaposlenicima
4. Odabrati svoj račun
5. Kliknuti na dugme "Obriši korisnika"

Dobijeni rezultat: 
Korisnik briše sam sebe

Očekivani rezultat: 
Nemogućnost brisanja samog sebe ili odjava sa računa kada korisnik obriše sam sebe

**Comment by kbalic1** [comment]
Rijesen issue sa commitom 9590cd
