### ISSUE TITLE
Nema poruke o uspješnosti odjave

### ISSUE THREAD

**Issue by enverpezic** [SoftverInzenjeringETFSA/SI2015Tim2#45]
Komponenta:
Menadzer home ili Uposlenik home

Opis problema:
Kada se bilo koji korisnik odjavi nema poruke o uspješnosti odjave. U srs-u je naglašeno da ima poruka o uspješnosti odjave.

Koraci za reproduciranje problema:
1.Pokrenuti desktop aplikaciju godisnji-odmori
2. Logovatin se na bilo koji postojeći račun
3. Kliknuti na dugme "Odjava"

Dobijeni rezultat: 
Nema poruke o uspješnosti odjave

Očekivani rezultat: 
Poruka o uspješnosti odjave

**Comment by kbalic1** [comment]
Rijesen issue sa commitom 763420d
