### ISSUE TITLE
Nema pregled statusa o svim podnesenim zahtjevima

### ISSUE THREAD

**Issue by enverpezic** [SoftverInzenjeringETFSA/SI2015Tim2#46]
Komponenta:
Korisnik home

Opis problema:
Korisnik sa privilegijama uposlenika nema pregled statusa svih zahtjeva koje je podnio. Navedeno je u srs-u da korisnik može pregledati status svih zahtjeva.
 
Koraci za reproduciranje problema:
1.Pokrenuti desktop aplikaciju godisnji-odmori
2. Logovati se kao uposlenik

Dobijeni rezultat: 
Nema mogućnosti da pregleda sve zahtjeve

Očekivani rezultat: 
Mogućnost da pregleda sve zahtjeve koje je podnio

**Comment by kbalic1** [comment]
Necemo ga raditi, jer od pocetka nismo pravili logiku za ovaj view tako da nam se ne isplati da ga uradimo.
