### ISSUE TITLE
Nemogućnost promjene tipa korisnika

### ISSUE THREAD

**Issue by enverpezic** [SoftverInzenjeringETFSA/SI2015Tim2#47]
Komponenta:
Menadzer home

Opis problema:
Kada menadzer uredjuje korisnike sa privilegijama "menadzera" i  prilikom uredjivanja promjeni njihov tip iz menadzera u uposlenika, prilikom prijave uredjeni korisnik se opet loguje kao menadzer, a ne kao obicni uposlenik, tj pojavljuje mu se forma za menadzera.

Koraci za reproduciranje problema:
1.Pokrenuti desktop aplikaciju godisnji-odmori
2. Logovati se kao menadzer
3. Kliknuti na tab uposlenici
4. Odabrati korisnika ciji je tip menadzer, i kliknuti na dugme "Uredi uposlenika"
5.  Tip odabranog korisnika promjeniti u tip uposlenika
6. Spasiti promjene, zatim se odjaviti
7. Logovat se kao korisnik kojem smo promjenili tip korisnika

Dobijeni rezultat: 
Korisnik nakon logovanja dobija formu za menadzera

Očekivani rezultat: 
Korisnik nakon logovanja treba dobiti formu za uposlenika

**Comment by kbalic1** [comment]
Rijesen issue sa commitom 803bcde
