### ISSUE TITLE
Ucitavanje podataka na tabovima

### ISSUE THREAD

**Issue by srepuh** [SoftverInzenjeringETFSA/SI2015Tim2#48]
Komponenta:
Zaposlenici tab

Opis problema:
Kada menadzer izbrise sektor, i prebaci na dodavanje novog zaposlenika u ponudi ostane stari sektor koji je izbrisan, tj. mora izaci iz aplikacije da bi sektor bio izbrisan iz liste sektora na tabu zaposlenik.

Koraci za reproduciranje problema:
1. Logovati se kao menadzer
2. Kliknuti na tab "Sektori" 
3. Kliknuti na listu sektora i obrisati jedan
4. Kliknuti na tab "Zaposlenici"
5. Kliknuti na combobox i provjeriti da li postoji izbrisani sektor

Dobijeni rezultat:
Postoji sektor koji je obrisan

Ocekivani rezultat:
Nema sektora koji sam prethodno obrisao

**Comment by kbalic1** [comment]
Dupliciran bug #32 , jer oba issue-a su zasnovana na tome da se lista ne osvježava nakon brisanja ili dodavanja sektora.
