### ISSUE TITLE
Nemogucnost uredjena informacija o zaposleniku

### ISSUE THREAD

**Issue by srepuh** [SoftverInzenjeringETFSA/SI2015Tim2#49]
Komponenta:
Editovanje zaposlenika

Opis problema:
Ukoliko izbrisemo sektor u kojem postoje uposlenici, zatim kliknemo na editovanje uposlenika koji je radio u obrisanom sektoru, pojavi se messagebox sa porukom da nije odabran uposlenik iako jeste
http://pokit.org/get/?dffeaebda328b7e82b4395cc3bcba1a9.jpg

Koraci za reproduciranje problema:
1. Logovati se kao menadzer
2. Kliknuti na tab "Sektori" 
3. Odabrati jedan sektor koji ima 1 ili vise zaposlenika i obrisati taj sektor
4. Kliknuti na tab "Zaposlenici"
5. Odabrati zaposlenika kojem pise "Nema sektora" 
6. Kliknuti "Uredi zaposlenika"

Dobijeni rezultat:
Poruka da nije odabran zaposlenik iako jeste

Ocekivani rezultat:
Mogucnost promjene informacija o zaposleniku

**Comment by kbalic1** [comment]
Rijesen issue commitom 60a03fe
