### ISSUE TITLE
Neusaglasenost koda i SRSa

### ISSUE THREAD

**Issue by srepuh** [SoftverInzenjeringETFSA/SI2015Tim2#50]
Commit:
876444f853a4e5ae8269cf7419926d96c0c9c856

Opis problema:
Korisnik sa privilegijama menadzera ne moze promjeniti svoju sifru, iako je u SRS-u navedeno da oba tipa korisnika mogu promjeniti svoju sifru.
http://pokit.org/get/?ad0660350772763da9a3bbd3a818a396.jpg

Koraci reproduciranja problema:
1. Logovanje kao menadzer
2. Kreiranje novog zaposlenika sa privilegijom menadzera
3. Odjava
4. Logovanje kao tek dodani menadzer

Dobijeni rezultat:
Nepostojeca forma za promjenu sifre korisnika koji je logovan kao menadzer

Ocekivani rezultat:
Da menadzer moze promjeniti sifru nakon sto se loguje kao menadzer

**Comment by kbalic1** [comment]
DA bi nam UI specifikacije ostale dosljedne, necemo ovaj issue odraditi, jer bi smo time narusili izgled aplikacije koji smo obecali.
