### ISSUE TITLE
Datum u godisnjem odmoru

### ISSUE THREAD

**Issue by dzemila** [SoftverInzenjeringETFSA/SI2015Tim2#51]
Komponenta:
Datum u Godisnjem odmoru

Commit ID:
864c35d

Opis problema:
Moguće je odabrati datum da godisnji pocinje u proslosti 

Koraci za reproduciranje problema:
1.Pokrenuti desktop aplikaciju godisnji-odmori
2.Logovati se kao Zaposlenik
3.Otvoriti tab Godisnji odmor
4.Za datum pocetka godisnjeg odabrati bilo koji datum u proslosti 

Dobijeni rezultat: Poruka o uspjesno prijavljenom godisnjem
Očekivani rezultat: Obavijest o nevalidnosti pocetka godisnjeg

**Comment by DinoBabahmetovic** [comment]
godisnji se moze evidentovati u bilo kojem vremenskom intervalu, sve je na odluci managera, primjer je slucaj da je zaposlenik otisao na godisnji a to nije bilo evidentovano u sistemu, on moze naknadno poslati zahtjev kako bi se to evidentovalo, a na manageru je da odluci

**Comment by dzemila** [comment]
Valjda se ovakav sistem pravi da bi se izbjegli "iznenadni" godisnji... jer je to onda neplanirano odsustvo a ne godisnji... inace bi se to u firmama trebalo "rezervisati" ranije. Tako da mi nije logicno da prvo odem na godisnji pa se onda prijavim dva dana pet dana ili vise dana poslije odlaska... ako je firma od 1000 zaposlenih ne vjerujem bas da to tako moze funkcionisati

**Comment by DinoBabahmetovic** [comment]
To je istina, ali se ovaj sistem pravi i da bude sto fleksibilniji :)
