### ISSUE TITLE
Nemogucnost logovanja 

### ISSUE THREAD

**Issue by dzemila** [SoftverInzenjeringETFSA/SI2015Tim2#52]
Komponenta:
ID u listi Zaposlenika

Commit ID:
864c35d

Opis problema:
Nakon poslanih zahtjeva i odjave sa racuna zaposlenika, pokusala sam se logovati kao administrator i ne ide odnosno izbaci gresku
![image](https://cloud.githubusercontent.com/assets/11327922/15377301/05335ee0-1d5b-11e6-9f19-142293575e66.png)

Koraci za reproduciranje problema:
1.Pokrenuti desktop aplikaciju godisnji-odmori
2.Logovati se kao zaposlenik
3."podnijeti" zahtjeve za godisnji bolovanje itd itd
4.Odjaviti se klikom na opciju Odjava
5.Ponovno se pokusati logovati ali ovaj put kao administrator, ukucati kao username admin i password admin

Dobijeni rezultat: Poruka s greskom
Očekivani rezultat: Pristup sistemu kao Administrator

**Comment by dzemila** [comment]
cak i kad izbrisem ostale iz baze i ostavim ovakvu situaciju
![image](https://cloud.githubusercontent.com/assets/11327922/15377484/4288897c-1d5c-11e6-8363-7603c798fd8a.png)

prijavi mi da ih ima vise 
![image](https://cloud.githubusercontent.com/assets/11327922/15377491/51765db0-1d5c-11e6-9da4-650eb9650377.png)

**Comment by kbalic1** [comment]
Dupliciran issue #26

**Comment by dzemila** [comment]
U issue-u #26 kolegici se desi da nakon drugog puta bude uspjesno prijavljen korisnik a u mom slucaju to nije bilo moguce ni nakon 10tog klika na dugme ok
Tako da issue nije dupliciran i to mi se desavalo prilikom pokusaja pristupa adminu a ne obicnom zaposleniku
