### ISSUE TITLE
Nepostojeća poruka nakon prikazivanja infoBox-a prilikom Login-a

### ISSUE THREAD

**Issue by ahusic** [SoftverInzenjeringETFSA/SI2015Tim2#53]
Komponenta:
Login forma

coomit ID :
65c2c2e

Opis problema:
Prilikom ponovne prijave aplikaciju, sa ispravnim login podacima, koji su predhodno uneseni kroz aplikaciju pojavljuje se infoBox bez sa naslovom : Greška, bez odgovarajućeg sadržaja poruke šta je greška i zašto je došlo do greške.

Koraci koji su vodili do problema:
1. Izvršena je prijava na sistem podacima admin admin
2.  izvršen unos 2 korisnika bez menažerske privilegije koji pripada sektoru administracije, jer je to bio jedini ponuđen sektor
3. izvršeno je dodavanje još sektora, nakon čega je obrisan sektor administracije. 
4.  Izvršena Odjava sa aplikacije
5. Login sa ispravnim podacima prethodno unesenim kroz aplikaciju
6.Klik na dugme Login 

Očekivani rezultat : adekvatnija poruka sa opisom i sadržajem

Prikaz izlaza aplikacije
![Prikaz izlaza aplikacije](https://cloud.githubusercontent.com/assets/11318471/15417113/b105c9d6-1e52-11e6-9447-5aa946fcf826.jpg)
Stanje u tabeli Zaposlenik
![uposlenik tabela podaci](https://cloud.githubusercontent.com/assets/11318471/15417127/ce992466-1e52-11e6-8690-10b05c30b78c.jpg)

**Comment by DinoBabahmetovic** [comment]
Ovo je kolegica greškom stavila bug, ovdje je invalid jer očigledno niste ispravno koristili našu aplikaciju.

**Comment by ahusic** [comment]
Šta se dešava sa korisnicima čiji je sektor obrisan. Zašto je moguće obrisat sektor koji ima korisnike. Objasnite mi zašto nije bug.  Šta znači ispravno koristiti Vašu aplikaciju. Definišite ispravno. Da li ispravno znači ne brisati sektor koji ima korisnike. Da li je to moja greška kao testera ili Vaša. Naravno vaša jer ste to dopustili, pri čemu čak ni poruka nije odgovarajuća uz sve te propuste.
