### ISSUE TITLE
Neodgovarajuća poruka nakon prikazivanja infoBox-a prilikom Login-a -LOGIN uspješan

### ISSUE THREAD

**Issue by ahusic** [SoftverInzenjeringETFSA/SI2015Tim2#54]
Komponenta:
Login forma

coomit ID :
65c2c2e

Opis problema:
Prilikom ponovne prijave aplikaciju, sa ispravnim login podacima admin admin, dolazi do pojave infoBox-a 
sa naslovom Greška i sadržajem: Korisnik sa username: admin ne postoji

Koraci koji su vodili do problema:
1. Izvršena je prijava na sistem podacima admin admin
2.  izvršen unos 2 korisnika bez menažerske privilegije koji pripada sektoru administracije, jer je to bio jedini ponuđen sektor
3. izvršeno je dodavanje još sektora, nakon čega je obrisan sektor administracije. 
4.  Izvršena Odjava sa aplikacije
5. izvršen ponovni login sa istim podacima admin admin
6.Klik na dugme Login 

Očekivani rezultat : Uspješan login bez prikazivanja ove poruke ili promjena poruke

Izlaz aplikacije
![korisnik sa username admin ne postoji](https://cloud.githubusercontent.com/assets/11318471/15417299/62fca4ba-1e54-11e6-9cbd-90f92cd7f43f.jpg)

Stanje tabele Zaposlenik u bazi
![uposlenik tabela podaci](https://cloud.githubusercontent.com/assets/11318471/15417127/ce992466-1e52-11e6-8690-10b05c30b78c.jpg)

**Comment by mersedaooad** [comment]
Duliciran issue broj #26

**Comment by ahusic** [comment]
Ova poruka nema nikakve veze sa tom porukom, kao ni redosljed radnji, vidio sam sve issuse 51 ukupno i pročitao prije pisanja, tako da. Nije duplikat.
