### ISSUE TITLE
Unos podataka u bazu nije jedinstven. Dozvoljen je višestruki unos zaposlenika sa identičnim podacima

### ISSUE THREAD

**Issue by ahusic** [SoftverInzenjeringETFSA/SI2015Tim2#55]
Komponenta:
Menadžer forma-tab Zaposlenici

commit ID :
65c2c2e

Opis problema:
Prilikom dodavanja zaposlenika, može se unijeti npr. 10 unosa sa istim podacima. Iako se korisničko ime i lozinka generišu na osnovu imena i prezimena i kao takvi unose u bazu. 10 istih unosa će se u bazi razlikovat samo u generisanim poljima korisničko ime i lozinka, što nikako nije ok. Na taj način imamo 10 ljudi koji rade u istom sektoru, ista im je adresa stanovanja, ista e-mail adresa, isti broj tel. imaju istu privilegiju i broj dana godišnjeg, ili to može biti 1 čovjek koji se može logovat na aplikaciju na 10 načina..(Ne može biti 10 braće blizanaca i živjet pod istim krovom i svi pričati na isti telefon.) 

Koraci koji su vodili do problema:
1. Izvršena je prijava na sistem podacima admin admin
2.  izvršen unos 5 korisnika sa istim podacim bez menažerske privilegije koji pripada sektoru administracije, 

Očekivani rezultat : Nemogućnost unosa 2 korisnika sa istim identičnim podacima

**Comment by mersedaooad** [comment]
Sto se tice dodavanja zaposlenika, u SRS-u ne pise da ne smiju biti sa istim podacima.
Kao sto Ste i sami rekli razlikuju se po sifri i korisnickom imenu, sto je u skladu sa SRS.

**Comment by ahusic** [comment]
Može ono biti da se slaže sa SRS-om vezano za šifru i korisničko ime i to je ok, to je ono što ste vi ispoštovali. Ono što je problem sam napisao. Postoji propust, sve je lijepo objašnjeno. Po vama nije bug imati istu osobu sa 10 različitih načina logovanja na aplikaciju..Hoćete mail poslat (mail je jedinstven), šta onda, ko prima taj mail..

**Comment by AyLLa93** [comment]
@ahusic Gdje se u aplikaciji šalje mail? Mail je opcionalna stvar, nije obavezna za unos u sistem :)
