### ISSUE TITLE
Validacija datuma ne postoji, donji opseg premašuje minimalni dozvoljeni unos godine

### ISSUE THREAD

**Issue by ahusic** [SoftverInzenjeringETFSA/SI2015Tim2#56]
Komponenta:
Login forma

coomit ID :
65c2c2e

Opis problema:
Prilikom odabira/unosa datuma rođenja moguće za broj godine unijeti  1888 ili 1555  što se ne smije dešavati. Minimalna donja granica kod unosa/odabira godine je 1900  a maksimalna gornja 2016, iako nije ograničen ni odozgo.

Koraci koji su vodili do problema:
1. Izvršena je prijava na sistem podacima admin admin
2.  izvršeno popunjavanje polja za dodavanje zaposlenika unutar taba Zaposlenici
5. Klik na dugme Dodaj zaposlenika
6 klik OK na.Uspješno dodavanje poruka

Izlaz aplikacije:
infoBox sa porukom o uspješnosti dodavanja 

Očekivani izlaz : konkretna poruka koja govori da unos/odabir godine mora biti u odgovarajućem rasponu 1900-trenutna godina

Stanje tabele Zaposlenik u bazi nakon unosa
![mmmmmmmmmmmmmmm](https://cloud.githubusercontent.com/assets/11318471/15418214/c627f022-1e5d-11e6-9f76-36c75c327674.jpg)

**Comment by mersedaooad** [comment]
Dupliciran issue #17

**Comment by ahusic** [comment]
Kolegice ako može da čitate prije nego duplicirate issue. DONJI OPSEG PREMAŠUJE MINIMALNI DOZVOLJENI UNOS GODINE..Issue #17 kaže da je moguće staviti datum na datum koji se nije dogodio, pročitao sam ga kao i sve ostalo. Ovi datumi su se dogodili o kojima ja pričam,  možemo za godinu rođenja uzet godinu iz srednjeg vijeka..
