### ISSUE TITLE
Dodavanje zaposlenika nakon vise unosenja

### ISSUE THREAD

**Issue by adnela** [SoftverInzenjeringETFSA/SI2015Tim2#57]
Komponenta: Dodavanje zaposlenika

commit ID: 
94aa13c

Nije moguće dodavanje zaposlenika nakon sto se unese 9 zaposlenika, čak ni nakon što se obrišu i u bazi ostane samo administrator

Koraci za reprodukciju problema:
1. Pokrenuti desktop aplikaciju godisnji-odmori
2. Logovati se ako administrator
3. Popuniti podatke a zatim kliknuti na dugme "Dodaj zaposlenika" 
Dobijeni rezultat: Nakon pritiska na dugme se isprazne textBox-evi, nema poruke o uspješnom dodavanju, niti se u bazi doda novi zaposlenik
Očekivan rezultat: Poruka o uspješnom dodavanju i dodavanje zaposlenika u bazu

**Comment by mersedaooad** [comment]
Nije preuzeta zadnja verzija projekta sa git-a
![image](https://cloud.githubusercontent.com/assets/11328979/15425893/7f41d35c-1e8b-11e6-8299-3117f241c224.png)

![image](https://cloud.githubusercontent.com/assets/11328979/15425906/8ce497ec-1e8b-11e6-8c01-2cca560693ec.png)
