### ISSUE TITLE
Validacija imena i prezimena prilikom narednih unosa ne postoji - dodavanje zaposlenika

### ISSUE THREAD

**Issue by ahusic** [SoftverInzenjeringETFSA/SI2015Tim2#58]
Menadžer forma-tab Zaposlenici

commit ID:
88c8840

Opis problema:
Prilikom unosa u polja Ime i Prezime kod dodavanja zaposlenika mogući su sljedeći unosi
-unos brojeva
-unos specijalnih karatkera
-unos samo whitespaceova 
-unos whitespaceova i znakova (       znakovi         )
-kombinacija svega navedenog
-unos samo jednog ili 2 znaka (ime minimalno ima 3 slova)
-unos je ograničen na 255 znakova u bazi i to bilo kojih, što nema smisla

primjeri uspješnih unosa:

Ime: 6+8519/2*2*
Prezime: *//--/-/-/--/-/-/*-/-/*/-
Ime:/)&F)&)/&F/)F/=//*-/-/-/**-/*_:;_;_;;:___;_;_:;:_;_:;:_;;_;_:_:;_:;_;/(T%/&%&/%&/%/%&/$$/$/&$
Prezime: "ovdje 10 whitespaceova &/%&(/& jos whitespaceova " 

Očekivani izlazi poruka u ovisnosti od tipa greške:

Nije dozvoljen unos brojeva u polje Ime/prezime.
Unos specijalnih znakova nije dozvoljen.
Nije dozvoljen unos whitespace-ova
Ime mora biti minalne dužine od 3 slova 
Vaš unos prekoračuje dozvoljeni limit od 25 slova.

**Comment by mersedaooad** [comment]
Prema SRS dokumentu, za uslove validnosti prilikom dodavanja zaposlenika samo se validiraju email i broj telefona, za ostalo nije receno.
Ukoliko se Vas issue odnosi i na email i broj telefona te greske su vec prijavljene.

**Comment by ahusic** [comment]
Znači, šta god nije navedeno u SRS-u eksplicitno koje uslove validnosti mora da zadovoljava, može da neispravno radi i to je OK. Ako vi tako kažete uredu, međutim ja sam uvažavao bugove ovog tipa i ispravljao ih, ukoliko su prijavljeni.
