### ISSUE TITLE
Unos novog sektora

### ISSUE THREAD

**Issue by ahusic** [SoftverInzenjeringETFSA/SI2015Tim2#59]
Komponenta: Menadžer forma- tab Sektori

commit ID : 88c8840

Opis problema:
Prilikom unosa novog sektora mogući su nedozvoljeni unosi u sljedeća polja:

Unosi koji prolaze u polju Naziv sektora:
-samo whitespaceovi ("                 ")
-whitespaceovi i znak (          j        )
-specijalni karatkeri (  /-/**--**/%% )
-brojevi
-unos dužine 1,2, 3 znaka, nema validacije minimalne dužine unosa
-unos dužine 255 znakova, nema validacije maksimalne dužine unos je ograničen opsegom u bazi

Unosi koji prolaze u polju Godina osnivanja:
-godina veća od trenutne godine (2020.) maksimalni unos je ograničen opsegom int-a, ukoliko se unese veliki broj npr. 99999999 u bazi se unosi kao 2147483647 
-bilo koja godina ukoliko je pozitivna, npr. unos 1 

Poruka vezano za grešku ispod polja Maksimalni broj odsutnih ljudi u jednom danu se ne vidi u cjelosti.
Greška uzrokovana unosom negativne vrijednosti.
poruka :"Polje maksimalan broj odsustva moze sadrzavat..."

Očekivani izlazi:
-Naziv sektora (poruka o opsegu unosa, poruka o pogrešnom tipu unosa podataka)
-Godina osnivanja ( poruka sa razumnim opisom raspona unosa godine, nemaju smisla unosi u budućnosti i u doba 2015 godina.) 
-Maksimalni broj odsutnih ljudi u jednom danu (Očekivano je da se poruka jasno vidi u cjelosti).

nakon svih ovih unosa imamo unesene sljedeće sektore :
![unosi sektora sa greskama](https://cloud.githubusercontent.com/assets/11318471/15431728/79a4d1b8-1eab-11e6-90a2-9169bf1a95a5.jpg)

stanje u bazi:
![stanje baze sa pogresnim unosom sektora](https://cloud.githubusercontent.com/assets/11318471/15431785/af34205e-1eab-11e6-9e47-4e38e80680ed.jpg)

**Comment by kbalic1** [comment]
Dupliciran issue #18 , a i problem sa datumom se spominje na vise mjesta u prethodnim issue-ima, a unos naziva necemo isrpavljati iz razloga sto tu ostavljamo slobodu menadzeru da daje nazive Sektorima kakve hoce, mozda bas iz nekog njemu poznatog razloga zeli da sektor imenuje kao "         j         ".
