### ISSUE TITLE
Promjena šifre zaposlenika

### ISSUE THREAD

**Issue by ahusic** [SoftverInzenjeringETFSA/SI2015Tim2#60]
Komponenta : Forma za zaposelnika - tab Informacije

commit ID: 88c8840

Opis problema: Moguće je izvršiti promjenu šifre zaposlenika na nedozvoljene vrijednosti i dužine, različite od generisane šifre koja je dodjeljena prilikom dodavanja zaposlenika.

Koraci za reproduciranje problema:
1. login na aplikaciju sa podacima admin admin
2. unutar tab-a Zaposlenici dodati jednog zaposlenika pri čemu checkbox Manager privilegije ostavimo neoznačenim
3. izvršimo odjavu i prijavimo se kao obični zaposlenik sa podacima koje smo dobili na infoBox-u nakon uspješnog dodavanja tog zaposlenika
 4. odemo na tab informacije - promjena šifre
5. unesemo staru šifru i za novu šifru možemo unijeti šta bilo i raspon dužine 1-255 znakova. Primjer validnih unosa su:
-šifra dužine od samo jednog znaka
-šifra sastavljena od jednog whitespace-a prilikom čega je moguće izvršiti login na aplikaciju bez kucanja šifre

prikaz promjene šifre u jedan whitespace:
![promjena sifre na jedan whitespace](https://cloud.githubusercontent.com/assets/11318471/15433634/6b2af826-1eb3-11e6-936d-a4c13b8a2ddb.jpg)

prikaz logovanja bez šifre nakon što je šifra zamjenjena jednim whitespace-om:
![login bez sifre](https://cloud.githubusercontent.com/assets/11318471/15433643/732e58f6-1eb3-11e6-925e-e1ab30d2fe36.jpg)

prikaz Stanja u bazi za navedeni slučaj:
![zapis korisnika u bazi sa praznom sifrom](https://cloud.githubusercontent.com/assets/11318471/15433824/37d77750-1eb4-11e6-81b4-d624caac8d01.jpg)

Ponovna promjena šifre od jednog whitespace-a na novu šifru nakon uspješnog logina
![promjena sifre sa jednog whitespace-a na normalnu](https://cloud.githubusercontent.com/assets/11318471/15433735/d47a1e10-1eb3-11e6-8ddf-28a2ab8969e2.jpg)

**Comment by mersedaooad** [comment]
Zaposlenik je ovlasten da mijenja sifru u bilo koju kombinaciju slova ili space. U SRS nije navedeno koji format sifre mora biti.

**Comment by ahusic** [comment]
Ovo je invalid je???? a nakon mene a #64 je OK i BUG. Ovo je Bug #64 je duplikat od ovog. Kolegice Merseda dosta sa ispranim komentarima, nije navedeno u SRS-u.

**Comment by AyLLa93** [comment]
Do mene je, ja sam slučajno na bug #64 stavila da je bug, umjesto duplikat, zamijenila sam labele. I ovaj bug je ispravljen - rijesen issue commitom bfc57f6.

**Comment by ahusic** [comment]
Nije problem, zahvaljujem vam. Samo nije bitno, jel ili nije navedeno sve u SRS-u bitno je  da li radi kako treba ili ne.

**Comment by AyLLa93** [comment]
Naravno da je bitno je li navedeno u SRS-u, zato što zahvaljujući SRS-u znamo da li radi kako treba da radi (da li nešto radi kako treba nije subjektivna stvar, već je definisana). U ovom slučaju, ova validacija šifre JESTE navedena u SRS-u i zato i jeste legitiman bug.

Ja se još jednom izvinjavam zbog neugodnosti, stvarno nisam vidjela.
