### ISSUE TITLE
Ne vidi se puni naziv sektora

### ISSUE THREAD

**Issue by ahusic** [SoftverInzenjeringETFSA/SI2015Tim2#61]
Komponenta: Zaposlenik forma- tab Početna

commit ID: 88c8840

Opis problema: Naziv sektora se ne vidi u cjelosti, ukoliko je duži od 10 slova.

![ne vidi se naziv sektora](https://cloud.githubusercontent.com/assets/11318471/15434319/8be3dce2-1eb6-11e6-8301-381f498de71f.jpg)

**Comment by mersedaooad** [comment]
Rijesen issue, commit ID 51734250e5e37350df64b7bd63249b42643eec52
