### ISSUE TITLE
Nemogucnost brisanjan zahtjeva

### ISSUE THREAD

**Issue by dzemila** [SoftverInzenjeringETFSA/SI2015Tim2#62]
Komponenta:
Zahtjevi

commit ID:
763420d

Opis problema:
Nemogucnost brisanja zahtjeva za bilo koji odmor ili bolovanje od strane zaposlenika

Koraci za reproduciranje problema:
1.Pokrenuti desktop aplikaciju godisnji-odmori
2.Logovati se kao zaposlenik
3.Ući u tab za odmor bolovanje ili odsustvo
4. Kreirati zahtjev

Dobijeni rezultat: Nemogucnost brisanja zahtjeva

Očekivani rezultat: Mogucnost brisanja zahtjeva

**Comment by AyLLa93** [comment]
Gdje smo napisali da ćemo omogućiti brisanje zahtjeva?

**Comment by AyLLa93** [comment]
Gdje smo napisali da ćemo omogućiti brisanje zahtjeva?

**Comment by dzemila** [comment]
![image](https://cloud.githubusercontent.com/assets/11327922/15448787/bdcc21be-1f6b-11e6-8267-dc9c52c72e00.png)
   
ovdje

**Comment by kbalic1** [comment]
Ovaj issue je validan ali slican kao #46 , za koji bi trebali da pravimo novi view za pregled koji bi sadrzavao i opciju brisanje.

**Comment by AyLLa93** [comment]
Ja i dalje nisam sigurna da je ovo baš bug, iz razloga što nigdje nismo napisali funkcionalni zahtjev za brisanje, niti smo nacrtali bilo koji dijagram u kojem se spominje brisanje zahtjeva, tako da sam ga label-ovala sa wontfix u svakom slučaju.
