### ISSUE TITLE
Odjavna poruka

### ISSUE THREAD

**Issue by dzemila** [SoftverInzenjeringETFSA/SI2015Tim2#63]
Komponenta:
Odjavna poruka

commit ID:
763420d

Opis problema:
U SRS-u pise da se nakon odjave korisnika pojavi poruka o uspjesnoj odjavi medjutim nema je

Koraci za reproduciranje problema:
1.Pokrenuti desktop aplikaciju godisnji-odmori
2.Logovati se kao zaposlenik 
3.Kliknuti na opciju odjavi se

Dobijeni rezultat: Login prozor

Očekivani rezultat: poruka o uspjesnoj odjavi

**Comment by AyLLa93** [comment]
Kod mene sve radi:
http://prntscr.com/b6ka33
http://prntscr.com/b6ka7v

**Comment by dzemila** [comment]
[ice_video_20160521-160527.zip](https://github.com/SoftverInzenjeringETFSA/SI2015Tim2/files/275887/ice_video_20160521-160527.zip)

**Comment by kbalic1** [comment]
Provjeri da li si povukla dobru verziju sa git-a, jer je ovaj bug ponovljen #45 , a svakako ispravljen.
Posto vidim i ove dvije greske prilikom prijave na app, otidji u bazu i uradi truncate svim tabelama pa probaj opet, naravno sa zadnjom verzijom aplikacije.
