### ISSUE TITLE
Nova sifra

### ISSUE THREAD

**Issue by dzemila** [SoftverInzenjeringETFSA/SI2015Tim2#64]
Komponenta:
Nova sifra

commit ID:
763420d

Opis problema:
U SRS-u pise da nova sifra treba imati minimalno 8 simbola i jedan broj medjutim postavila sam da je sifra "nova"

Koraci za reproduciranje problema:
1.Pokrenuti desktop aplikaciju godisnji-odmori
2.Logovati se kao zaposlenik 
3.Otvoriti tab Informacije
4. unijeti staru sifru 
5. unijeti novu sifru samo slova npr "nova"

Dobijeni rezultat: uspjesno promijenjena sifra

Očekivani rezultat: poruka o gresci

**Comment by kbalic1** [comment]
Rijesen issue commitom bfc57f6.
